# The action goal

std_msgs/String mode
std_msgs/String state 
geometry_msgs/Point[] path

---
# Action result
geometry_msgs/PoseStamped pose_stamped 
std_msgs/String state 

---
# Action feedback
geometry_msgs/PoseStamped pose_stamped
std_msgs/String state 
