# The action goal

string controller 
string state 
geometry_msgs/Point[] path

---
# Action result
geometry_msgs/PoseStamped pose_stamped 
string state 

---
# Action feedback
geometry_msgs/PoseStamped pose_stamped
string state 
