# State
geometry_msgs/PoseStamped pose
geometry_msgs/TwistStamped twist
sensor_msgs/Imu imu_data

# The points to travel to 
geometry_msgs/Point[] path 
---
# Return the fifth degree polynomial coefficients with timestamp for each row, each polynomial 
# The splines are (N, 6) matrices, while timestamps are an (N + 1, 1) vectors

Spline[] splines
